name: Build Reference Documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-reference-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
